# Generated by Django 3.1.9 on 2021-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_page', '0002_auto_20210719_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
