# Generated by Django 3.1.9 on 2021-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_page', '0004_auto_20210719_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_from',
            field=models.CharField(max_length=50),
        ),
    ]
