# Generated by Django 3.1.9 on 2021-07-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_page', '0008_auto_20210719_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='company',
            new_name='school',
        ),
    ]
