# Generated by Django 3.1.9 on 2021-07-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_page', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
